# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b52b76b19a9b601e449fbc5e95841d133866973bed5924a1ce56de9cbc9c08e5ed75af92f12058af7cf1257fcfff4c08bc0437d23a3342952b387cc47f16550f

test:
  secret_key_base: b65bf2a43ecb8a010a58a2c68464694b0a779157123296e53d8727c1de475d7340238d1e1886f30cfb08edbfbc974eca099ddd138f8d22dd73c66b56190193f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
